# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "Seeding Users"

User.create(name: "user1", email: "user1@example.com")
User.create(name: "user2", email: "user2@example.com")
User.create(name: "user3", email: "user3@example.com")
User.create(name: "user4", email: "user4@example.com")
User.create(name: "user5", email: "user5@example.com")
User.create(name: "user6", email: "user6@example.com")
User.create(name: "user7", email: "user7@example.com")
User.create(name: "user8", email: "user8@example.com")
User.create(name: "user9", email: "user9@example.com")
User.create(name: "user10", email: "user10@example.com")
User.create(name: "user11", email: "user11@example.com")
User.create(name: "user12", email: "user12@example.com")
User.create(name: "user13", email: "user13@example.com")
User.create(name: "user14", email: "user14@example.com")
User.create(name: "user15", email: "user15@example.com")
User.create(name: "user16", email: "user16@example.com")
User.create(name: "user17", email: "user17@example.com")
User.create(name: "user18", email: "user18@example.com")
User.create(name: "user19", email: "user19@example.com")
User.create(name: "user20", email: "user20@example.com")
User.create(name: "user21", email: "user21@example.com")
User.create(name: "user22", email: "user22@example.com")
User.create(name: "user23", email: "user23@example.com")
User.create(name: "user24", email: "user24@example.com")
User.create(name: "user25", email: "user25@example.com")
User.create(name: "user26", email: "user26@example.com")
User.create(name: "user27", email: "user27@example.com")
User.create(name: "user28", email: "user28@example.com")
User.create(name: "user29", email: "user29@example.com")
User.create(name: "user30", email: "user30@example.com")
User.create(name: "user31", email: "user31@example.com")
User.create(name: "user32", email: "user32@example.com")
User.create(name: "user33", email: "user33@example.com")
User.create(name: "user34", email: "user34@example.com")
User.create(name: "user35", email: "user35@example.com")
User.create(name: "user36", email: "user36@example.com")
User.create(name: "user37", email: "user37@example.com")
User.create(name: "user38", email: "user38@example.com")
User.create(name: "user39", email: "user39@example.com")
User.create(name: "user40", email: "user40@example.com")
User.create(name: "user41", email: "user41@example.com")
User.create(name: "user42", email: "user42@example.com")
User.create(name: "user43", email: "user43@example.com")
User.create(name: "user44", email: "user44@example.com")
User.create(name: "user45", email: "user45@example.com")
User.create(name: "user46", email: "user46@example.com")

puts "Seeding Restaurants"

Restaurant.create(yelp_id: "east-side-marios-nepean-2")
Restaurant.create(yelp_id: "nu-caribbean-kanata")
Restaurant.create(yelp_id: "gezellig-ottawa")
Restaurant.create(yelp_id: "the-works-gourmet-burger-bistro-ottawa-7")
Restaurant.create(yelp_id: "amuse-kitchen-and-wine-ottawa")
Restaurant.create(yelp_id: "yangtze-ottawa")
Restaurant.create(yelp_id: "play-food-and-wine-ottawa")
Restaurant.create(yelp_id: "host-india-ottawa")
Restaurant.create(yelp_id: "burgers-n-fries-forever-ottawa-2")
Restaurant.create(yelp_id: "zaks-diner-ottawa")
Restaurant.create(yelp_id: "jericho-lebanese-food-ottawa")
Restaurant.create(yelp_id: "the-wellington-diner-ottawa")
Restaurant.create(yelp_id: "the-third-ottawa")
Restaurant.create(yelp_id: "bistro-ristoro-ottawa")
Restaurant.create(yelp_id: "ahora-mexican-cuisine-ottawa")
Restaurant.create(yelp_id: "the-green-door-vegetarian-restaurant-ottawa")
Restaurant.create(yelp_id: "coras-breakfast-and-lunch-ottawa")
Restaurant.create(yelp_id: "merivale-fish-market-nepean-2")
Restaurant.create(yelp_id: "corner-peach-ottawa")
Restaurant.create(yelp_id: "chez-lucien-ottawa")
Restaurant.create(yelp_id: "moo-shu-ice-cream-and-kitchen-ottawa")
Restaurant.create(yelp_id: "the-belmont-ottawa")
Restaurant.create(yelp_id: "wilf-and-adas-ottawa")
Restaurant.create(yelp_id: "mhk-sushi-ottawa")
Restaurant.create(yelp_id: "the-king-eddy-ottawa")
Restaurant.create(yelp_id: "isabella-pizzeria-ottawa")
Restaurant.create(yelp_id: "pho-bo-ga-2-ottawa-2")
Restaurant.create(yelp_id: "grunt-ottawa")
Restaurant.create(yelp_id: "east-india-company-ottawa")
Restaurant.create(yelp_id: "common-eatery-ottawa")
Restaurant.create(yelp_id: "weis-noodle-house-ottawa")
Restaurant.create(yelp_id: "koichi-ramen-ottawa")
Restaurant.create(yelp_id: "sushi-umi-ottawa")
Restaurant.create(yelp_id: "nh-44-ottawa")
Restaurant.create(yelp_id: "flora-hall-brewing-ottawa-2")
Restaurant.create(yelp_id: "fauna-food-bar-ottawa")
Restaurant.create(yelp_id: "casa-mexico-ottawa")
Restaurant.create(yelp_id: "talay-thai-ottawa")
Restaurant.create(yelp_id: "hanabi-japanese-cuisine-ottawa")
Restaurant.create(yelp_id: "the-foolish-chicken-ottawa")
Restaurant.create(yelp_id: "ten-sushi-buffet-ottawa")
Restaurant.create(yelp_id: "il-negozio-nicastro-ottawa")
Restaurant.create(yelp_id: "fraser-cafe-ottawa")
Restaurant.create(yelp_id: "pressed-ottawa")
Restaurant.create(yelp_id: "fratelli-westboro-ottawa")
Restaurant.create(yelp_id: "pancho-villa-ottawa")
Restaurant.create(yelp_id: "hintonburger-ottawa")
Restaurant.create(yelp_id: "montanas-bbq-and-bar-gloucester")
Restaurant.create(yelp_id: "erlings-variety-ottawa")
Restaurant.create(yelp_id: "kochin-kitchen-ottawa")
Restaurant.create(yelp_id: "mamma-teresa-ristorante-ottawa")
Restaurant.create(yelp_id: "tomaso-grilled-pizza-and-panini-kanata")
Restaurant.create(yelp_id: "lexington-ottawa")
Restaurant.create(yelp_id: "pure-kitchen-preston-ottawa")
Restaurant.create(yelp_id: "dolsot-cafe-ottawa")
Restaurant.create(yelp_id: "north-and-navy-ottawa")
Restaurant.create(yelp_id: "la-bottega-nicastro-fine-food-shop-ottawa")
Restaurant.create(yelp_id: "asian-alley-ottawa")
Restaurant.create(yelp_id: "coconut-lagoon-ottawa")
Restaurant.create(yelp_id: "blue-nile-ottawa")
Restaurant.create(yelp_id: "cacao-70-ottawa")
Restaurant.create(yelp_id: "168-sushi-buffet-ottawa")
Restaurant.create(yelp_id: "the-village-house-wakefield")
Restaurant.create(yelp_id: "elgin-street-diner-ottawa")
Restaurant.create(yelp_id: "bennys-bistro-ottawa")
Restaurant.create(yelp_id: "la-cabaña-ottawa")
Restaurant.create(yelp_id: "restaurant-18-ottawa-2")
Restaurant.create(yelp_id: "occo-kitchen-innes-ottawa")
Restaurant.create(yelp_id: "vanier-grill-vanier")
Restaurant.create(yelp_id: "the-manx-ottawa")
Restaurant.create(yelp_id: "cest-japon-à-suisha-ottawa-2")
Restaurant.create(yelp_id: "atelier-ottawa")
Restaurant.create(yelp_id: "khao-thai-restaurant-ottawa")
Restaurant.create(yelp_id: "wolf-down-ottawa")
Restaurant.create(yelp_id: "south-st-burger-nepean")
Restaurant.create(yelp_id: "haldi-east-indian-cuisine-ottawa")
Restaurant.create(yelp_id: "charlotte-ottawa")
Restaurant.create(yelp_id: "riviera-ottawa")
Restaurant.create(yelp_id: "new-shawarma-king-ottawa-2")
Restaurant.create(yelp_id: "burrito-sensei-ottawa-2")
Restaurant.create(yelp_id: "dreamland-cafe-ottawa-3")
Restaurant.create(yelp_id: "newport-restaurant-ottawa-2")
Restaurant.create(yelp_id: "pita-bell-kabab-ottawa")
Restaurant.create(yelp_id: "the-soca-kitchen-ottawa-2")
Restaurant.create(yelp_id: "dumpling-bowl-ottawa")
Restaurant.create(yelp_id: "luxe-bistro-ottawa")
Restaurant.create(yelp_id: "ceylonta-restaurant-ottawa")
Restaurant.create(yelp_id: "grow-your-roots-ottawa")
Restaurant.create(yelp_id: "churchills-ottawa")
Restaurant.create(yelp_id: "broadway-bar-and-grill-central-nepean")
Restaurant.create(yelp_id: "co-cham-restaurant-ottawa")
Restaurant.create(yelp_id: "meat-press-ottawa-2")
Restaurant.create(yelp_id: "joey-rideau-ottawa")
Restaurant.create(yelp_id: "perfection-satisfaction-promise-ottawa-2")
Restaurant.create(yelp_id: "fatboys-southern-smokehouse-ottawa")
Restaurant.create(yelp_id: "wangs-noodle-house-ottawa")
Restaurant.create(yelp_id: "dairy-queen-grill-and-chill-ottawa-2")
Restaurant.create(yelp_id: "sweet-basil-restaurant-ottawa")
Restaurant.create(yelp_id: "thali-ottawa")
Restaurant.create(yelp_id: "chatime-ottawa-3")
Restaurant.create(yelp_id: "the-rowan-ottawa")
Restaurant.create(yelp_id: "pizarros-restaurant-vanier")
Restaurant.create(yelp_id: "salang-kabob-house-ottawa")
Restaurant.create(yelp_id: "sidedoor-contemporary-kitchen-and-bar-ottawa")
Restaurant.create(yelp_id: "datsun-ottawa")
Restaurant.create(yelp_id: "table-sodam-ottawa")
Restaurant.create(yelp_id: "citizen-ottawa-2")
Restaurant.create(yelp_id: "island-grill-ottawa")
Restaurant.create(yelp_id: "shawarma-palace-ottawa")
Restaurant.create(yelp_id: "pub-italia-ottawa")
Restaurant.create(yelp_id: "absinthe-cafe-ottawa")
Restaurant.create(yelp_id: "tennessy-willems-ottawa")
Restaurant.create(yelp_id: "kanata-noodle-house-ottawa")
Restaurant.create(yelp_id: "prime-burger-bar-ottawa")
Restaurant.create(yelp_id: "ben-ben-restaurant-ottawa")
Restaurant.create(yelp_id: "yang-sheng-restaurant-ottawa")
Restaurant.create(yelp_id: "el-camino-ottawa")
Restaurant.create(yelp_id: "colonnade-pizza-ottawa-5")
Restaurant.create(yelp_id: "sansotei-ramen-ottawa")
Restaurant.create(yelp_id: "ola-cocina-ottawa")
Restaurant.create(yelp_id: "mcdonalds-ottawa-15")
Restaurant.create(yelp_id: "so-good-restaurant-ottawa")
Restaurant.create(yelp_id: "roast-n-curries-ottawa")
Restaurant.create(yelp_id: "namaste-india-ottawa")
Restaurant.create(yelp_id: "saigon-restaurant-ottawa")
Restaurant.create(yelp_id: "shanghai-restaurant-ottawa")
Restaurant.create(yelp_id: "mehfil-indian-cuisine-ottawa")
Restaurant.create(yelp_id: "the-smoque-shack-ottawa")
Restaurant.create(yelp_id: "chahaya-malaysia-gloucester")
Restaurant.create(yelp_id: "petit-bills-bistro-ottawa")
Restaurant.create(yelp_id: "anthonys-ottawa")
Restaurant.create(yelp_id: "ginza-ramen-sushi-and-sake-bar-ottawa")
Restaurant.create(yelp_id: "suzyq-doughnuts-ottawa")
Restaurant.create(yelp_id: "cheshire-cat-pub-ottawa")
Restaurant.create(yelp_id: "gongfu-bao-ottawa")
Restaurant.create(yelp_id: "mekong-restaurant-ottawa")
Restaurant.create(yelp_id: "supply-and-demand-ottawa")
Restaurant.create(yelp_id: "poco-pazzo-kanata")
Restaurant.create(yelp_id: "beckta-dining-and-wine-ottawa-2")
Restaurant.create(yelp_id: "the-royal-oak-ottawa-10")
Restaurant.create(yelp_id: "nandos-ottawa")
Restaurant.create(yelp_id: "mandarin-restaurant-nepean-nepean-2")
Restaurant.create(yelp_id: "the-glen-ottawa-2")
Restaurant.create(yelp_id: "cosmo-bar-gatineau")
Restaurant.create(yelp_id: "rangoon-restaurant-ottawa-4")
Restaurant.create(yelp_id: "chez-fatima-gatineau")
Restaurant.create(yelp_id: "art-is-in-bakery-ottawa-2")
Restaurant.create(yelp_id: "les-grillades-ottawa-2")
Restaurant.create(yelp_id: "lone-star-texas-grill-ottawa-9")
Restaurant.create(yelp_id: "the-whalesbone-ottawa")
Restaurant.create(yelp_id: "das-lokal-ottawa")
Restaurant.create(yelp_id: "mati-ottawa")
Restaurant.create(yelp_id: "edgar-gatineau-2")
Restaurant.create(yelp_id: "union-local-613-ottawa-2")
Restaurant.create(yelp_id: "giovannis-ottawa")
Restaurant.create(yelp_id: "veras-burger-shack-ottawa")
Restaurant.create(yelp_id: "corazón-de-maíz-ottawa-2")
Restaurant.create(yelp_id: "the-brig-pub-ottawa")
Restaurant.create(yelp_id: "sushi-88-ottawa")
Restaurant.create(yelp_id: "siam-bistro-ottawa")
Restaurant.create(yelp_id: "town-ottawa")
Restaurant.create(yelp_id: "aroma-meze-ottawa")
Restaurant.create(yelp_id: "viet-thai-noodle-soup-restaurant-ottawa")
Restaurant.create(yelp_id: "princess-shawarma-ottawa")
Restaurant.create(yelp_id: "dal-moros-fresh-pasta-to-go-ottawa-2")
Restaurant.create(yelp_id: "bambu-restaurant-ottawa")
Restaurant.create(yelp_id: "istanbouli-shawarma-house-ottawa-2")
Restaurant.create(yelp_id: "oz-kafe-ottawa")
Restaurant.create(yelp_id: "bar-laurel-ottawa")
Restaurant.create(yelp_id: "izakaya-shingen-ottawa")
Restaurant.create(yelp_id: "oriental-chu-shing-restaurant-ottawa-2")
Restaurant.create(yelp_id: "takeout-king-ottawa")
Restaurant.create(yelp_id: "the-fry-ottawa")
Restaurant.create(yelp_id: "el-furniture-warehouse-ottawa-ottawa-2")
Restaurant.create(yelp_id: "sterling-gatineau")

puts "Seeding Favorites"

Favorite.create(user_id: 1, restaurant_id: 58)
Favorite.create(user_id: 1, restaurant_id: 165)
Favorite.create(user_id: 1, restaurant_id: 100)
Favorite.create(user_id: 1, restaurant_id: 57)
Favorite.create(user_id: 1, restaurant_id: 121)
Favorite.create(user_id: 2, restaurant_id: 83)
Favorite.create(user_id: 2, restaurant_id: 163)
Favorite.create(user_id: 2, restaurant_id: 131)
Favorite.create(user_id: 2, restaurant_id: 42)
Favorite.create(user_id: 3, restaurant_id: 117)
Favorite.create(user_id: 3, restaurant_id: 54)
Favorite.create(user_id: 3, restaurant_id: 13)
Favorite.create(user_id: 3, restaurant_id: 139)
Favorite.create(user_id: 3, restaurant_id: 56)
Favorite.create(user_id: 3, restaurant_id: 136)
Favorite.create(user_id: 3, restaurant_id: 150)
Favorite.create(user_id: 3, restaurant_id: 126)
Favorite.create(user_id: 3, restaurant_id: 153)
Favorite.create(user_id: 3, restaurant_id: 19)
Favorite.create(user_id: 3, restaurant_id: 70)
Favorite.create(user_id: 3, restaurant_id: 159)
Favorite.create(user_id: 3, restaurant_id: 66)
Favorite.create(user_id: 3, restaurant_id: 99)
Favorite.create(user_id: 3, restaurant_id: 59)
Favorite.create(user_id: 4, restaurant_id: 68)
Favorite.create(user_id: 4, restaurant_id: 7)
Favorite.create(user_id: 4, restaurant_id: 3)
Favorite.create(user_id: 4, restaurant_id: 117)
Favorite.create(user_id: 4, restaurant_id: 96)
Favorite.create(user_id: 4, restaurant_id: 139)
Favorite.create(user_id: 4, restaurant_id: 86)
Favorite.create(user_id: 4, restaurant_id: 67)
Favorite.create(user_id: 4, restaurant_id: 104)
Favorite.create(user_id: 4, restaurant_id: 16)
Favorite.create(user_id: 4, restaurant_id: 111)
Favorite.create(user_id: 4, restaurant_id: 150)
Favorite.create(user_id: 4, restaurant_id: 27)
Favorite.create(user_id: 4, restaurant_id: 63)
Favorite.create(user_id: 5, restaurant_id: 30)
Favorite.create(user_id: 5, restaurant_id: 137)
Favorite.create(user_id: 5, restaurant_id: 117)
Favorite.create(user_id: 5, restaurant_id: 105)
Favorite.create(user_id: 6, restaurant_id: 46)
Favorite.create(user_id: 6, restaurant_id: 98)
Favorite.create(user_id: 6, restaurant_id: 128)
Favorite.create(user_id: 6, restaurant_id: 26)
Favorite.create(user_id: 6, restaurant_id: 124)
Favorite.create(user_id: 7, restaurant_id: 5)
Favorite.create(user_id: 7, restaurant_id: 105)
Favorite.create(user_id: 7, restaurant_id: 152)
Favorite.create(user_id: 7, restaurant_id: 36)
Favorite.create(user_id: 7, restaurant_id: 147)
Favorite.create(user_id: 8, restaurant_id: 49)
Favorite.create(user_id: 8, restaurant_id: 8)
Favorite.create(user_id: 8, restaurant_id: 69)
Favorite.create(user_id: 8, restaurant_id: 97)
Favorite.create(user_id: 8, restaurant_id: 148)
Favorite.create(user_id: 8, restaurant_id: 90)
Favorite.create(user_id: 8, restaurant_id: 140)
Favorite.create(user_id: 9, restaurant_id: 154)
Favorite.create(user_id: 9, restaurant_id: 28)
Favorite.create(user_id: 9, restaurant_id: 92)
Favorite.create(user_id: 9, restaurant_id: 65)
Favorite.create(user_id: 9, restaurant_id: 20)
Favorite.create(user_id: 10, restaurant_id: 14)
Favorite.create(user_id: 10, restaurant_id: 10)
Favorite.create(user_id: 10, restaurant_id: 150)
Favorite.create(user_id: 10, restaurant_id: 78)
Favorite.create(user_id: 10, restaurant_id: 95)
Favorite.create(user_id: 10, restaurant_id: 151)
Favorite.create(user_id: 11, restaurant_id: 36)
Favorite.create(user_id: 11, restaurant_id: 78)
Favorite.create(user_id: 11, restaurant_id: 161)
Favorite.create(user_id: 11, restaurant_id: 73)
Favorite.create(user_id: 11, restaurant_id: 43)
Favorite.create(user_id: 12, restaurant_id: 117)
Favorite.create(user_id: 12, restaurant_id: 151)
Favorite.create(user_id: 12, restaurant_id: 53)
Favorite.create(user_id: 12, restaurant_id: 93)
Favorite.create(user_id: 12, restaurant_id: 152)
Favorite.create(user_id: 12, restaurant_id: 161)
Favorite.create(user_id: 12, restaurant_id: 78)
Favorite.create(user_id: 13, restaurant_id: 74)
Favorite.create(user_id: 13, restaurant_id: 54)
Favorite.create(user_id: 13, restaurant_id: 23)
Favorite.create(user_id: 13, restaurant_id: 117)
Favorite.create(user_id: 13, restaurant_id: 105)
Favorite.create(user_id: 13, restaurant_id: 64)
Favorite.create(user_id: 13, restaurant_id: 158)
Favorite.create(user_id: 14, restaurant_id: 3)
Favorite.create(user_id: 14, restaurant_id: 117)
Favorite.create(user_id: 14, restaurant_id: 62)
Favorite.create(user_id: 14, restaurant_id: 9)
Favorite.create(user_id: 14, restaurant_id: 71)
Favorite.create(user_id: 15, restaurant_id: 172)
Favorite.create(user_id: 15, restaurant_id: 174)
Favorite.create(user_id: 15, restaurant_id: 64)
Favorite.create(user_id: 15, restaurant_id: 132)
Favorite.create(user_id: 15, restaurant_id: 119)
Favorite.create(user_id: 15, restaurant_id: 113)
Favorite.create(user_id: 16, restaurant_id: 137)
Favorite.create(user_id: 16, restaurant_id: 117)
Favorite.create(user_id: 16, restaurant_id: 55)
Favorite.create(user_id: 16, restaurant_id: 105)
Favorite.create(user_id: 16, restaurant_id: 170)
Favorite.create(user_id: 17, restaurant_id: 34)
Favorite.create(user_id: 17, restaurant_id: 103)
Favorite.create(user_id: 17, restaurant_id: 137)
Favorite.create(user_id: 17, restaurant_id: 130)
Favorite.create(user_id: 17, restaurant_id: 87)
Favorite.create(user_id: 17, restaurant_id: 3)
Favorite.create(user_id: 17, restaurant_id: 150)
Favorite.create(user_id: 17, restaurant_id: 145)
Favorite.create(user_id: 18, restaurant_id: 10)
Favorite.create(user_id: 18, restaurant_id: 150)
Favorite.create(user_id: 18, restaurant_id: 161)
Favorite.create(user_id: 18, restaurant_id: 43)
Favorite.create(user_id: 18, restaurant_id: 157)
Favorite.create(user_id: 18, restaurant_id: 78)
Favorite.create(user_id: 18, restaurant_id: 119)
Favorite.create(user_id: 18, restaurant_id: 54)
Favorite.create(user_id: 19, restaurant_id: 78)
Favorite.create(user_id: 19, restaurant_id: 169)
Favorite.create(user_id: 19, restaurant_id: 154)
Favorite.create(user_id: 19, restaurant_id: 105)
Favorite.create(user_id: 19, restaurant_id: 117)
Favorite.create(user_id: 19, restaurant_id: 43)
Favorite.create(user_id: 19, restaurant_id: 101)
Favorite.create(user_id: 19, restaurant_id: 119)
Favorite.create(user_id: 19, restaurant_id: 84)
Favorite.create(user_id: 19, restaurant_id: 72)
Favorite.create(user_id: 20, restaurant_id: 18)
Favorite.create(user_id: 20, restaurant_id: 167)
Favorite.create(user_id: 20, restaurant_id: 72)
Favorite.create(user_id: 20, restaurant_id: 27)
Favorite.create(user_id: 20, restaurant_id: 54)
Favorite.create(user_id: 20, restaurant_id: 133)
Favorite.create(user_id: 20, restaurant_id: 33)
Favorite.create(user_id: 20, restaurant_id: 17)
Favorite.create(user_id: 20, restaurant_id: 40)
Favorite.create(user_id: 20, restaurant_id: 118)
Favorite.create(user_id: 20, restaurant_id: 80)
Favorite.create(user_id: 20, restaurant_id: 37)
Favorite.create(user_id: 20, restaurant_id: 74)
Favorite.create(user_id: 21, restaurant_id: 141)
Favorite.create(user_id: 21, restaurant_id: 159)
Favorite.create(user_id: 21, restaurant_id: 22)
Favorite.create(user_id: 21, restaurant_id: 122)
Favorite.create(user_id: 21, restaurant_id: 19)
Favorite.create(user_id: 21, restaurant_id: 79)
Favorite.create(user_id: 21, restaurant_id: 32)
Favorite.create(user_id: 21, restaurant_id: 38)
Favorite.create(user_id: 21, restaurant_id: 51)
Favorite.create(user_id: 21, restaurant_id: 171)
Favorite.create(user_id: 21, restaurant_id: 115)
Favorite.create(user_id: 21, restaurant_id: 85)
Favorite.create(user_id: 22, restaurant_id: 149)
Favorite.create(user_id: 22, restaurant_id: 99)
Favorite.create(user_id: 22, restaurant_id: 128)
Favorite.create(user_id: 22, restaurant_id: 164)
Favorite.create(user_id: 22, restaurant_id: 62)
Favorite.create(user_id: 22, restaurant_id: 67)
Favorite.create(user_id: 23, restaurant_id: 54)
Favorite.create(user_id: 23, restaurant_id: 135)
Favorite.create(user_id: 23, restaurant_id: 74)
Favorite.create(user_id: 23, restaurant_id: 56)
Favorite.create(user_id: 23, restaurant_id: 19)
Favorite.create(user_id: 23, restaurant_id: 32)
Favorite.create(user_id: 23, restaurant_id: 15)
Favorite.create(user_id: 23, restaurant_id: 44)
Favorite.create(user_id: 23, restaurant_id: 128)
Favorite.create(user_id: 23, restaurant_id: 162)
Favorite.create(user_id: 24, restaurant_id: 16)
Favorite.create(user_id: 24, restaurant_id: 72)
Favorite.create(user_id: 24, restaurant_id: 20)
Favorite.create(user_id: 24, restaurant_id: 154)
Favorite.create(user_id: 24, restaurant_id: 139)
Favorite.create(user_id: 25, restaurant_id: 161)
Favorite.create(user_id: 25, restaurant_id: 25)
Favorite.create(user_id: 25, restaurant_id: 59)
Favorite.create(user_id: 25, restaurant_id: 102)
Favorite.create(user_id: 25, restaurant_id: 125)
Favorite.create(user_id: 26, restaurant_id: 3)
Favorite.create(user_id: 26, restaurant_id: 150)
Favorite.create(user_id: 26, restaurant_id: 131)
Favorite.create(user_id: 26, restaurant_id: 121)
Favorite.create(user_id: 26, restaurant_id: 121)
Favorite.create(user_id: 26, restaurant_id: 121)
Favorite.create(user_id: 26, restaurant_id: 121)
Favorite.create(user_id: 26, restaurant_id: 10)
Favorite.create(user_id: 26, restaurant_id: 119)
Favorite.create(user_id: 26, restaurant_id: 132)
Favorite.create(user_id: 26, restaurant_id: 9)
Favorite.create(user_id: 26, restaurant_id: 105)
Favorite.create(user_id: 26, restaurant_id: 62)
Favorite.create(user_id: 26, restaurant_id: 106)
Favorite.create(user_id: 26, restaurant_id: 77)
Favorite.create(user_id: 27, restaurant_id: 78)
Favorite.create(user_id: 27, restaurant_id: 135)
Favorite.create(user_id: 27, restaurant_id: 31)
Favorite.create(user_id: 27, restaurant_id: 39)
Favorite.create(user_id: 28, restaurant_id: 71)
Favorite.create(user_id: 28, restaurant_id: 55)
Favorite.create(user_id: 28, restaurant_id: 11)
Favorite.create(user_id: 28, restaurant_id: 23)
Favorite.create(user_id: 28, restaurant_id: 59)
Favorite.create(user_id: 28, restaurant_id: 147)
Favorite.create(user_id: 29, restaurant_id: 54)
Favorite.create(user_id: 29, restaurant_id: 88)
Favorite.create(user_id: 29, restaurant_id: 146)
Favorite.create(user_id: 29, restaurant_id: 109)
Favorite.create(user_id: 29, restaurant_id: 74)
Favorite.create(user_id: 29, restaurant_id: 41)
Favorite.create(user_id: 29, restaurant_id: 166)
Favorite.create(user_id: 29, restaurant_id: 9)
Favorite.create(user_id: 29, restaurant_id: 29)
Favorite.create(user_id: 30, restaurant_id: 127)
Favorite.create(user_id: 30, restaurant_id: 108)
Favorite.create(user_id: 30, restaurant_id: 159)
Favorite.create(user_id: 30, restaurant_id: 129)
Favorite.create(user_id: 30, restaurant_id: 115)
Favorite.create(user_id: 31, restaurant_id: 78)
Favorite.create(user_id: 31, restaurant_id: 137)
Favorite.create(user_id: 31, restaurant_id: 104)
Favorite.create(user_id: 31, restaurant_id: 67)
Favorite.create(user_id: 31, restaurant_id: 30)
Favorite.create(user_id: 32, restaurant_id: 1)
Favorite.create(user_id: 32, restaurant_id: 61)
Favorite.create(user_id: 32, restaurant_id: 29)
Favorite.create(user_id: 32, restaurant_id: 106)
Favorite.create(user_id: 32, restaurant_id: 123)
Favorite.create(user_id: 33, restaurant_id: 119)
Favorite.create(user_id: 33, restaurant_id: 7)
Favorite.create(user_id: 33, restaurant_id: 127)
Favorite.create(user_id: 33, restaurant_id: 35)
Favorite.create(user_id: 34, restaurant_id: 72)
Favorite.create(user_id: 34, restaurant_id: 135)
Favorite.create(user_id: 34, restaurant_id: 112)
Favorite.create(user_id: 34, restaurant_id: 65)
Favorite.create(user_id: 34, restaurant_id: 52)
Favorite.create(user_id: 34, restaurant_id: 81)
Favorite.create(user_id: 35, restaurant_id: 160)
Favorite.create(user_id: 35, restaurant_id: 45)
Favorite.create(user_id: 35, restaurant_id: 24)
Favorite.create(user_id: 35, restaurant_id: 76)
Favorite.create(user_id: 35, restaurant_id: 9)
Favorite.create(user_id: 35, restaurant_id: 112)
Favorite.create(user_id: 35, restaurant_id: 130)
Favorite.create(user_id: 36, restaurant_id: 64)
Favorite.create(user_id: 36, restaurant_id: 6)
Favorite.create(user_id: 36, restaurant_id: 113)
Favorite.create(user_id: 36, restaurant_id: 141)
Favorite.create(user_id: 36, restaurant_id: 142)
Favorite.create(user_id: 37, restaurant_id: 4)
Favorite.create(user_id: 37, restaurant_id: 9)
Favorite.create(user_id: 37, restaurant_id: 114)
Favorite.create(user_id: 37, restaurant_id: 75)
Favorite.create(user_id: 37, restaurant_id: 47)
Favorite.create(user_id: 37, restaurant_id: 156)
Favorite.create(user_id: 37, restaurant_id: 25)
Favorite.create(user_id: 38, restaurant_id: 16)
Favorite.create(user_id: 38, restaurant_id: 70)
Favorite.create(user_id: 38, restaurant_id: 159)
Favorite.create(user_id: 38, restaurant_id: 168)
Favorite.create(user_id: 38, restaurant_id: 119)
Favorite.create(user_id: 38, restaurant_id: 161)
Favorite.create(user_id: 38, restaurant_id: 94)
Favorite.create(user_id: 38, restaurant_id: 20)
Favorite.create(user_id: 38, restaurant_id: 150)
Favorite.create(user_id: 39, restaurant_id: 12)
Favorite.create(user_id: 39, restaurant_id: 173)
Favorite.create(user_id: 39, restaurant_id: 23)
Favorite.create(user_id: 39, restaurant_id: 116)
Favorite.create(user_id: 39, restaurant_id: 103)
Favorite.create(user_id: 40, restaurant_id: 59)
Favorite.create(user_id: 40, restaurant_id: 137)
Favorite.create(user_id: 40, restaurant_id: 143)
Favorite.create(user_id: 40, restaurant_id: 65)
Favorite.create(user_id: 40, restaurant_id: 20)
Favorite.create(user_id: 40, restaurant_id: 82)
Favorite.create(user_id: 40, restaurant_id: 21)
Favorite.create(user_id: 40, restaurant_id: 74)
Favorite.create(user_id: 40, restaurant_id: 162)
Favorite.create(user_id: 41, restaurant_id: 56)
Favorite.create(user_id: 41, restaurant_id: 57)
Favorite.create(user_id: 41, restaurant_id: 89)
Favorite.create(user_id: 41, restaurant_id: 59)
Favorite.create(user_id: 41, restaurant_id: 175)
Favorite.create(user_id: 42, restaurant_id: 43)
Favorite.create(user_id: 42, restaurant_id: 101)
Favorite.create(user_id: 42, restaurant_id: 91)
Favorite.create(user_id: 42, restaurant_id: 19)
Favorite.create(user_id: 42, restaurant_id: 150)
Favorite.create(user_id: 42, restaurant_id: 161)
Favorite.create(user_id: 42, restaurant_id: 107)
Favorite.create(user_id: 42, restaurant_id: 169)
Favorite.create(user_id: 42, restaurant_id: 3)
Favorite.create(user_id: 42, restaurant_id: 67)
Favorite.create(user_id: 42, restaurant_id: 19)
Favorite.create(user_id: 42, restaurant_id: 120)
Favorite.create(user_id: 42, restaurant_id: 117)
Favorite.create(user_id: 43, restaurant_id: 48)
Favorite.create(user_id: 43, restaurant_id: 83)
Favorite.create(user_id: 43, restaurant_id: 144)
Favorite.create(user_id: 43, restaurant_id: 119)
Favorite.create(user_id: 43, restaurant_id: 33)
Favorite.create(user_id: 44, restaurant_id: 10)
Favorite.create(user_id: 44, restaurant_id: 174)
Favorite.create(user_id: 44, restaurant_id: 78)
Favorite.create(user_id: 44, restaurant_id: 106)
Favorite.create(user_id: 44, restaurant_id: 50)
Favorite.create(user_id: 45, restaurant_id: 155)
Favorite.create(user_id: 45, restaurant_id: 60)
Favorite.create(user_id: 45, restaurant_id: 29)
Favorite.create(user_id: 45, restaurant_id: 72)
Favorite.create(user_id: 45, restaurant_id: 150)
Favorite.create(user_id: 46, restaurant_id: 134)
Favorite.create(user_id: 46, restaurant_id: 4)
Favorite.create(user_id: 46, restaurant_id: 110)
Favorite.create(user_id: 46, restaurant_id: 138)
Favorite.create(user_id: 46, restaurant_id: 2)